
include:
  - compose/plex.yml
  - compose/tautulli.yml

services:
  plex:
    image: plexinc/pms-docker:latest # Set specific: plexinc/pms-docker:1.40.2.8395-c67dce28e
    container_name: plex
    network_mode: host # Change this to 'bridge' to define ports, example ports below
    #ports:
      #- 32400:32400/tcp
      #- 8324:8324/tcp
      #- 32469:32469/tcp
      #- 1900:1900/udp
      #- 32410:32410/udp
      #- 32412:32412/udp
      #- 32413:32413/udp
      #- 32414:32414/udp
    # Uncomment the devices section for tv tuners and intel gpus
    #devices:
      #- /dev/dvb:/dev/dvb # Uncomment this device for typical USB TV Tuner cards
      #- /dev/dri:/dev/dri # Uncomment this to use intel GPUs for Hardware Transcoding
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles # Change this to match your server's timezone
      - PLEX_CLAIM=claim-P6bWYPs3UM6NK8pHY5RL # Uncomment this to setup Plex server, get your claim code from here - https://www.plex.tv/claim/
      # Uncomment the lines below to use Nvidia GPUs for Hardware Transcoding
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sync the container's time to the host's time
      - ./config/plexdata:/config # Plex server application data is stored in a folder called 'plexmediaserver' in the same directory as the docker-compose.yaml file
      # Uncomment the lines below for each library,
      # make sure the path on the left of the colon (:) exists on the host! `/mnt/tv`
      - /share/data:/data
      #- /mnt/transcode:/mnt/transcode
    restart: unless-stopped

#  nginx: 
#    image: 'jc21/nginx-proxy-manager:latest'
#    container_name: nginx-proxy-manager
#    ports:
#      - '80:80'
#      - '8081:81'
#      - '443:443'
#    volumes:
#      - /share/data/config/nrp/data:/data
#      - /share/data/config/nrp/letsencrypt:/etc/letsencrypt

  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/share/data/config/jdownloader:/config:rw"
      - "/share/data/downloads:/output:rw"
